% add subfolder with required functions from MATLAB to search path
addpath(genpath(pwd))
mkdir('rawdata')

%% define different scenarios
% '' - main scenario: both animals and plants fitness-dependent disperse,
% 50 species, 3 patches.
% The following modified scenario are based on the main scenario:
% 'pltiso_' - isolate plant scenario. plants can not disperse
% 'pltrand_' - random plant dispersal scenario. plants disperse randomly
% 'p6_' - 6 patches
% 'noepsilon_' - a scenario without tendency to stay (i.e. epsilon = 0)
scenarioCell = {'','pltiso_','pltrand_', 'p6_', 'noepsilon_'};
snr = scenarioCell{1};  % main text used scenario 1 (main scenario)

if strcmp(snr, '')
    repList = 1:500;  % 500 reps for main scenario
else
    repList = 1:50;  % 50 for others
end

%% simulate differante dispersal modes (takes very long)
% under different habitat heterogeneity level H (and fix m0=0.1)
% output: sprintf('./rawdata/%srep%03d_diff_H.mat',snr,ir)
main_simulate(snr, 'H', repList)
% under different habitat connectivity level m0 (and fix H=0.6)
% output: sprintf('./rawdata/%srep%03d_diff_m0.mat',snr,ir)
if ismember('a', scenarioCell(1:3))
    main_simulate(snr, 'm0', repList)
end

%% data synthesis
% analyse raw equilibrium abundance data
% require: rawdata generated by simulation above
% output: sprintf('./%sres.mat',snr)
processdata(snr)

%% draw figures
% main text figures and sup figures S4-14
% require: sprintf('./%sres.mat',snr) generated by data synthesis above
% output: unarranged figures in figpath = sprintf('%sfigures',snr)
drawfig(snr)

% sup figures 1-3 and figures in supplement Text
% require: enough reps of raw abundance data in folder "rawdata",
% output: unarranged figures in folder "figures", starting with "sup_"
if strcmp(snr, '')
    drawfig_sup
end
